# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dongseok Im
title: Post-doctoral Researcher
email: dsim@kaist.ac.kr
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: dongseok-im-b05007216
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: lds1235566
# googleplus_username: +jekyll
orcid_username: 0000-0002-5856-8921
googlescholar_username: 7qThsfUAAAAJ


#additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://scholar.google.com/citations?user=7qThsfUAAAAJ&hl=en

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: ds_image.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Postdoctoral Researcher at KAIST Information & Electronics Research Institute, South Korea.
  My research interests are (1) energy-efficient **2D/3D vision system-on-chip** designs, 
  (2) **digital circuit-, architecture-, and SW-level AI accelerator** designs,
  and (3) **custom silicon chip and demonstration system board** designs.

  My Professional Skills:
  - Verilog, C/C++, Python, MATLAB, Java (Android API), C# (Unity API)
  - Tensorflow, Pytorch
  - Semi-custom Design Flow in Synopsys
  - FPGA (Altera/Xilinx) Design Tool Chains
  - Schematic Design in OrCAD Capture
  - SoC Platform Design with RISC-V ISA

content:

  ## Contents for HPCA 2024
  - title: Materials of HPCA 2024 Conference (March 2024) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: "1. LUTein: Dense-Sparse Bit-slice Architecture with Radix-4 LUT-based Slice-Tensor Processing Units"
        description: | # this will include new lines to allow paragraphs          
        [Paper Download](LUTein Dense-Sparse Bit-slice Architecture with Radix-4 LUT-based Slice-Tensor Processing Units.pdf)
         
          
      - layout: top
        title: "2. Sibia: Signed Bit-slice Architecture for Dense DNN Acceleration with Slice-level Sparsity Exploitation"
        description: | # this will include new lines to allow paragraphs
          [Paper Download](Sibia_Signed_Bit-slice_Architecture_for_Dense_DNN_Acceleration_with_Slice-level_Sparsity_Exploitation.pdf)

      - layout: top
        title: "3. HNPU: An Adaptive DNN Training Processor Utilizing Stochastic Dynamic Fixed-Point and Active Bit-Precision Searching"
        description: | # this will include new lines to allow paragraphs
          [Paper Download](HNPU_An_Adaptive_DNN_Training_Processor_Utilizing_Stochastic_Dynamic_Fixed-Point_and_Active_Bit-Precision_Searching.pdf)
          
  ## Contents for HPCA 2024


  - title: Education
    layout: text
    content: | # this will include new lines to allow paragraphs

      - **Postdoc. in Information & Electronics Research Institute, Korea Advanced Institute of Science and Technology (KAIST)**
        
        *Sep. 2023 - Present* 
    
      - **Ph.D. in Electrical Engineering, Korea Advanced Institute of Science and Technology (KAIST)**

        Thesis Title: A Low-Power and Real-Time 3-D Object Recognition System-on-chip
        
        *Mar. 2020 - Aug. 2023* 
        
        Advisor: Hoi-Jun Yoo 
      
      - **M.S. in Electrical Engineering, Korea Advanced Institute of Science and Technology (KAIST)**
        
        *Feb. 2018 - Feb. 2020* 
        
        Advisor: Hoi-Jun Yoo
        
      - **B.S. in Electrical Engineering, Pohang University of Science and Technology (POSTECH)**
        
        *Mar. 2014 - Feb. 2018*


  - title: First Authored Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HPCA 2024
        sub_title: IEEE International Symposium on High-Performance Computer Architecture
        caption: March 2024
        description: | # this will include new lines to allow paragraphs
          **<font color='#FF0000'>(New)</font> LUTein: Dense-Sparse Bit-slice Architecture with Radix-4 LUT-based Slice-Tensor Processing Units**
       
          *<ins>Dongseok Im</ins> and Hoi-Jun Yoo*

          To be published

      - layout: left
        title: Micro Journal
        sub_title: IEEE Micro
        caption: May-June 2023
        description: | # this will include new lines to allow paragraphs
          **A Mobile 3-D Object Recognition Processor With Deep-Learning-Based Monocular Depth Estimation**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Zhiyong Li, Junha Ryu, Sanghoon Kang, Donghyeon Han, Jinsu Lee, Wonhoon Park, Hankyul Kwon, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/10065511)

      - layout: left
        title: HPCA 2023
        sub_title: IEEE International Symposium on High-Performance Computer Architecture
        caption: March 2023
        description: | # this will include new lines to allow paragraphs
          **Sibia: Signed Bit-slice Architecture for Dense DNN Acceleration with Slice-level Sparsity Exploitation**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Zhiyong Li, Junha Ryu, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/10071031)

      - layout: left
        title: JSSC Journal
        sub_title: IEEE Journal of Solid-State Circuits
        caption: January 2023
        description: | # this will include new lines to allow paragraphs
          **DSPU: An Efficient Deep Learning-Based Dense RGB-D Data Acquisition with Sensor Fusion and 3-D Perception SoC**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Junha Ryu, Zhiyong Li, Sanghoon Kang, Donghyeon Han, Jinsu Lee, Wonhoon Park, Hankyul Kwon, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9943545)

      - layout: left
        title: HOT CHIPS 2022
        sub_title: IEEE Hot Chips Symposium
        caption: August 2022
        description: | # this will include new lines to allow paragraphs
          **DSPU: A 281.6mW Real-Time Deep Learning-Based Dense RGB-D Data Acquisition with Sensor Fusion and 3D Perception System-on-Chip**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Zhiyong Li, Junha Ryu, Sanghoon Kang, Donghyeon Han, Jinsu Lee, Wonhoon Park, Hankyul Kwon, and Hoi-Jun Yoo*

          [PPT Link](https://ieeexplore.ieee.org/document/9895605)

      - layout: left
        title: COOL CHIPS 2022
        sub_title: IEEE Symposium on Low-Power and High-Speed Chips and Systems
        caption: April 2022
        description: | # this will include new lines to allow paragraphs
          **A Low-power and Real-time 3D Object Recognition Processor with Dense RGB-D Data Acquisition in Mobile Platforms**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Junha Ryu, Zhiyong Li, Sanghoon Kang, Donghyeon Han, Jinsu Lee, Wonhoon Park, Hankyul Kwon, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9772667)

      - layout: left
        title: ISSCC 2022
        sub_title: IEEE International Conference on Solid-State Circuits
        caption: February 2022
        description: | # this will include new lines to allow paragraphs
          **DSPU: A 281.6mW Real-Time Depth Signal Processing Unit for Deep Learning-Based Dense RGB-D Data Acquisition with Depth Fusion and 3D Bounding Box Extraction in Mobile Platforms**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Zhiyong Li, Junha Ryu, Sanghoon Kang, Donghyeon Han, Jinsu Lee, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9731699), [Demo Video](https://youtu.be/QC3Jmih_X1c?si=1CAydp_tFFkxeeaF), [News](https://ee.kaist.ac.kr/ai-in-circuit/dspu-a-281-6mw-real-time-depth-signal-processing-unit-for-deep-learning-based-dense-rgb-d-data-acquisition-with-depth-fusion-and-3d-bounding-box-extraction-in-mobile-platforms-%EC%9C%A0%ED%9A%8C/)

      - layout: left
        title: JSSC Journal
        sub_title: IEEE Journal of Solid-State Circuits
        caption: February 2022
        description: | # this will include new lines to allow paragraphs
          **A Pipelined Point Cloud Based Neural Network Processor for 3-D Vision With Large-Scale Max Pooling Layer Prediction**
       
          *<ins>Dongseok Im</ins>, Sanghoon Kang, Donghyeon Han, Sungpil Choi, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9466156)
          
      - layout: left
        title: TCAS-1 Journal
        sub_title: "IEEE Transactions on Circuits and Systems I: Regular Papers"
        caption: October 2020
        description: | # this will include new lines to allow paragraphs
          **DT-CNN: An energy-efficient dilated and transposed convolutional neural network processor for region of interest based image segmentation**
       
          *<ins>Dongseok Im</ins>, Donghyeon Han, Sungpil Choi, Sanghoon Kang, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9094335)

      - layout: left
        title: S.VLSI 2020
        sub_title: IEEE Symposium on VLSI Technology and Circuits
        caption: June 2020
        description: | # this will include new lines to allow paragraphs
          **A 4.45 ms Low-latency 3D Point-cloud-based Neural Network Processor for Hand Pose Estimation in Immersive Wearable Devices**
       
          *<ins>Dongseok Im</ins>, Sanghoon Kang, Donghyeon Han, Sungpil Choi, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9162895)

      - layout: left
        title: ISCAS 2019
        sub_title: IEEE International Symposium on Circuits and Systems
        caption: May 2019
        description: | # this will include new lines to allow paragraphs
          **DT-CNN: Dilated and transposed convolution neural network accelerator for real-time image segmentation on mobile devices**
       
          *<ins>Dongseok Im</ins>, Donghyeon Han, Sungpil Choi, Sanghoon Kang, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/8702243)



  - title: Awards & Scholarships
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **ISOCC Chip Design Contest Dest Poster Award**, *2022*
      - **Microsoft Research Asia Fellowship Nomination Award**, *2022*
      - **IEEE Solid-State Circuits Society ISSCC Student Travel Grant Award**, *2022*
      - **28th Samsung HumanTech Paper Award (Circuit Design) Bronze Prize**, *2022*
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
