# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dongseok Im
title: Post-doctoral Researcher
email: dsim@kaist.ac.kr / LDS1235566@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: dongseok-im-b05007216
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: lds1235566
# googleplus_username: +jekyll
orcid_username: 0000-0002-5856-8921
googlescholar_username: 7qThsfUAAAAJ


#additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://scholar.google.com/citations?user=7qThsfUAAAAJ&hl=en

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: ds_image2.jpg
about_content: | # this will include new lines to allow paragraphs
  ## I received the Ph.D. degree in electrical engineering from the Korea Advanced Institute of Science and Technology (KAIST), South Korea. I am currently a Postdoctoral Researcher at KAIST Information & Electronics Research Institute. 
  ## My research interests are (1) energy-efficient **2D/3D vision system-on-chip** designs, (2) **digital circuit-, architecture-, and SW-level AI accelerator** designs, and (3) **custom silicon chip and demonstration system board** designs.


content:

  ## Contents for HPCA 2024
  - title: "News" # Title for the section 
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        
        title: "(Updated: Feb 2025) New US Patent Application"
        description: | # this will include new lines to allow paragraphs   
          ## **- STEREOSCOPIC 360-DEGREE IMAGE/VIDEO GENERATION AND 3D DISPLAY SYSTEM**
          
          <img src="stereoscopic_360_degree_system.jpg" width="75%" height="75%" title="CamPU Architecture" alt="absolute"/>           

          ## A stereoscopic 360-degree image/video generation and 3D display system includes a generation platform configured to generate a stereoscopic 360-degree image/video by inferring a disparity map from a 360-degree image/video, and a display platform configured to perform three-dimensional (3D) display on a 3D display device by scanning the stereoscopic 360-degree image/video generated by the generation platform.  The stereoscopic 360-degree image/video generation and 3D display system is divided into a stereoscopic 360-degree image/video generation platform that requires high throughput and a platform that three-dimensionally displays a low-latency stereoscopic 360-degree image/video, and thus has an effect of being able to efficiently achieve a platform configuration and hardware design for satisfying requirements in each platform.
      
     #   title: "(Updated: July 2024) New Paper Accepted at MICRO-57"
     #   description: | # this will include new lines to allow paragraphs   
     #     ## **- CamPU: A Multi-Camera Processing Unit for Deep Learning-based 3D Spatial Computing Systems**
     #
     #     <img src="campu.png" width="75%" height="75%" title="CamPU Architecture" alt="absolute"/>           
     #     
     #     ## My recent research has been accepted at the 57th IEEE/ACM International Symposium on Microarchitecture (MICRO-57).
          
        
      #- layout: top
      #  title: "(Updated: Feb 2024) Open to Work"
      #  description: | # this will include new lines to allow paragraphs   
      #    *** I am open to work (Date Available for Work: Mar. 2025)**
      #    
      #    [CV](dongseok_cv.pdf)
          
  ## Contents for HPCA 2024
  ## **<font color='#FF0000'>(New)</font> LUTein: Dense-Sparse Bit-slice Architecture with Radix-4 LUT-based Slice-Tensor Processing Units**

      

  - title: First Authored Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MICRO 2024
        sub_title: IEEE/ACM International Symposium on Microarchitecture
        caption: November 2024
        description: | # this will include new lines to allow paragraphs                    
          ## ** CamPU: A Multi-Camera Processing Unit for Deep Learning-based 3D Spatial Computing Systems**
          # ## **<font color='#FF0000'>(New)</font> CamPU: A Multi-Camera Processing Unit for Deep Learning-based 3D Spatial Computing Systems**
       
          *<ins>Dongseok Im</ins> and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/abstract/document/10764609)
    
      - layout: left
        title: HPCA 2024
        sub_title: IEEE International Symposium on High-Performance Computer Architecture
        caption: March 2024
        description: | # this will include new lines to allow paragraphs                    
          ## **LUTein: Dense-Sparse Bit-slice Architecture with Radix-4 LUT-based Slice-Tensor Processing Units**
       
          *<ins>Dongseok Im</ins> and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/abstract/document/10476468)

      - layout: left
        title: Micro Journal
        sub_title: IEEE Micro
        caption: May-June 2023
        description: | # this will include new lines to allow paragraphs
          ## **A Mobile 3-D Object Recognition Processor With Deep-Learning-Based Monocular Depth Estimation**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Zhiyong Li, Junha Ryu, Sanghoon Kang, Donghyeon Han, Jinsu Lee, Wonhoon Park, Hankyul Kwon, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/10065511)

      - layout: left
        title: HPCA 2023
        sub_title: IEEE International Symposium on High-Performance Computer Architecture
        caption: March 2023
        description: | # this will include new lines to allow paragraphs
          ## **Sibia: Signed Bit-slice Architecture for Dense DNN Acceleration with Slice-level Sparsity Exploitation**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Zhiyong Li, Junha Ryu, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/10071031)

      - layout: left
        title: JSSC Journal
        sub_title: IEEE Journal of Solid-State Circuits
        caption: January 2023
        description: | # this will include new lines to allow paragraphs
          ## **DSPU: An Efficient Deep Learning-Based Dense RGB-D Data Acquisition with Sensor Fusion and 3-D Perception SoC**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Junha Ryu, Zhiyong Li, Sanghoon Kang, Donghyeon Han, Jinsu Lee, Wonhoon Park, Hankyul Kwon, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9943545)

      - layout: left
        title: HOT CHIPS 2022
        sub_title: IEEE Hot Chips Symposium
        caption: August 2022
        description: | # this will include new lines to allow paragraphs
          ## **DSPU: A 281.6mW Real-Time Deep Learning-Based Dense RGB-D Data Acquisition with Sensor Fusion and 3D Perception System-on-Chip**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Zhiyong Li, Junha Ryu, Sanghoon Kang, Donghyeon Han, Jinsu Lee, Wonhoon Park, Hankyul Kwon, and Hoi-Jun Yoo*

          [PPT Link](https://ieeexplore.ieee.org/document/9895605)

      - layout: left
        title: COOL CHIPS 2022
        sub_title: IEEE Symposium on Low-Power and High-Speed Chips and Systems
        caption: April 2022
        description: | # this will include new lines to allow paragraphs
          ## **A Low-power and Real-time 3D Object Recognition Processor with Dense RGB-D Data Acquisition in Mobile Platforms**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Junha Ryu, Zhiyong Li, Sanghoon Kang, Donghyeon Han, Jinsu Lee, Wonhoon Park, Hankyul Kwon, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9772667)

      - layout: left
        title: ISSCC 2022
        sub_title: IEEE International Conference on Solid-State Circuits
        caption: February 2022
        description: | # this will include new lines to allow paragraphs
          ## **DSPU: A 281.6mW Real-Time Depth Signal Processing Unit for Deep Learning-Based Dense RGB-D Data Acquisition with Depth Fusion and 3D Bounding Box Extraction in Mobile Platforms**
       
          *<ins>Dongseok Im</ins>, Gwangtae Park, Zhiyong Li, Junha Ryu, Sanghoon Kang, Donghyeon Han, Jinsu Lee, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9731699), [Demo Video](https://youtu.be/QC3Jmih_X1c?si=1CAydp_tFFkxeeaF), [News](https://ee.kaist.ac.kr/ai-in-circuit/dspu-a-281-6mw-real-time-depth-signal-processing-unit-for-deep-learning-based-dense-rgb-d-data-acquisition-with-depth-fusion-and-3d-bounding-box-extraction-in-mobile-platforms-%EC%9C%A0%ED%9A%8C/)

      - layout: left
        title: JSSC Journal
        sub_title: IEEE Journal of Solid-State Circuits
        caption: February 2022
        description: | # this will include new lines to allow paragraphs
          ## **A Pipelined Point Cloud Based Neural Network Processor for 3-D Vision With Large-Scale Max Pooling Layer Prediction**
       
          *<ins>Dongseok Im</ins>, Sanghoon Kang, Donghyeon Han, Sungpil Choi, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9466156)
          
      - layout: left
        title: TCAS-1 Journal
        sub_title: "IEEE Transactions on Circuits and Systems I: Regular Papers"
        caption: October 2020
        description: | # this will include new lines to allow paragraphs
          ## **DT-CNN: An energy-efficient dilated and transposed convolutional neural network processor for region of interest based image segmentation**
       
          *<ins>Dongseok Im</ins>, Donghyeon Han, Sungpil Choi, Sanghoon Kang, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9094335)

      - layout: left
        title: S.VLSI 2020
        sub_title: IEEE Symposium on VLSI Technology and Circuits
        caption: June 2020
        description: | # this will include new lines to allow paragraphs
          ## **A 4.45 ms Low-latency 3D Point-cloud-based Neural Network Processor for Hand Pose Estimation in Immersive Wearable Devices**
       
          *<ins>Dongseok Im</ins>, Sanghoon Kang, Donghyeon Han, Sungpil Choi, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/9162895)

      - layout: left
        title: ISCAS 2019
        sub_title: IEEE International Symposium on Circuits and Systems
        caption: May 2019
        description: | # this will include new lines to allow paragraphs
          ## **DT-CNN: Dilated and transposed convolution neural network accelerator for real-time image segmentation on mobile devices**
       
          *<ins>Dongseok Im</ins>, Donghyeon Han, Sungpil Choi, Sanghoon Kang, and Hoi-Jun Yoo*

          [Paper Link](https://ieeexplore.ieee.org/document/8702243)


  - title: 3D Video Projects
    layout: text
    content: | # this will include new lines to allow paragraphs
          ## **- 360° 3D VR Videos**

          <iframe width="320" height="240" src="https://www.youtube.com/embed/R8Hr2UyMb-8" frameborder="0" allowfullscreen></iframe> <iframe width="320" height="240" src="https://www.youtube.com/embed/_aKuJZCHHpU" frameborder="0" allowfullscreen></iframe> <iframe width="320" height="240" src="https://www.youtube.com/embed/YCJpa6C7F6w" frameborder="0" allowfullscreen></iframe> 
          ## This 360-degree 3D VR video projects a single 360-degree video into perspective views corresponding to human eyes with 3D depth effects through AI technology. The left video is captured through a dual-fisheye lens camera, and the right video is synthesized by applying depth to an original left scene. This project is run on a single RTX2080Ti card. The synthesis of a 360-degree 3D VR video takes 1 second per frame without any AI network finetunning. Left and right rendering displays take a total of 50 ms of latency as a view changes. Play VR videos on a Google Cardboard or AR/VR devices.
          
          ## **- 3D VR Videos**
          
          <iframe width="320" height="240" src="https://www.youtube.com/embed/kFTGVyA-P4w" frameborder="0" allowfullscreen></iframe> <iframe width="320" height="240" src="//www.youtube.com/embed/wKWDi_IAPno" frameborder="0" allowfullscreen></iframe> <iframe width="320" height="240" src="https://www.youtube.com/embed/6O2CfkIu6O0" frameborder="0" allowfullscreen></iframe> 
          ## This project generates 3D VR videos from a single video through AI technology. The right video is synthesized from the left one fitting in different perspective views of human eyes. This project is run on a single RTX2080Ti card. The Synthesis of the right side video takes 0.3 seconds per frame without any AI network finetunning. Play VR videos on a Google Cardboard or AR/VR devices.

          ## **- 3D Glasses Videos**

          <iframe width="320" height="240" src="https://www.youtube.com/embed/GxQthbuRe-I" frameborder="0" allowfullscreen></iframe> <iframe width="320" height="240" src="https://www.youtube.com/embed/e9_BszpIbkM" frameborder="0" allowfullscreen></iframe> <iframe width="320" height="240" src="https://www.youtube.com/embed/-Pzr-7ZGU0I" frameborder="0" allowfullscreen></iframe>
          ## This project generates 3D Glasses videos from a single video through AI technology. Red and Cyan colors are separated from an original video, and pixels corresponding to Cyan colors are shifted based on a depth map for 3D effects. Play this video with Red-Cyan anaglyph glasses.

          ## **- 3D Photos**
          
          <iframe width="320" height="240" src="https://www.youtube.com/embed/bI3rzMsBVl0" frameborder="0" allowfullscreen></iframe> <iframe width="320" height="240" src="https://www.youtube.com/embed/uxKrRniZif8" frameborder="0" allowfullscreen></iframe> <iframe width="320" height="240" src="https://www.youtube.com/embed/GLnWiT9vhgY" frameborder="0" allowfullscreen></iframe> 
          ## This project generates 3D photos from a single image through AI technology. This 3D effect provides a novel view synthesis that looks left and right.

  - title: Work Experience
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## **Postdoctoral Researcher at KAIST Information & Electronics Research Institute**          

      **[Recent Project]** Designing high-performance hardware architectures for multi-camera AI-based 3D spatial computing systems
        
      *Sep. 2023 - Current*       

  - title: Education
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## **- Ph.D. in Electrical Engineering, Korea Advanced Institute of Science and Technology (KAIST)**

        Thesis Title: A Low-Power and Real-Time 3-D Object Recognition System-on-chip
        
        *Mar. 2020 - Aug. 2023* 
        
        Advisor: Hoi-Jun Yoo 
      
      ## **- M.S. in Electrical Engineering, Korea Advanced Institute of Science and Technology (KAIST)**
        
        *Feb. 2018 - Feb. 2020* 
        
        Advisor: Hoi-Jun Yoo
        
      ## **- B.S. in Electrical Engineering, Pohang University of Science and Technology (POSTECH)**
        
        *Mar. 2014 - Feb. 2018*


  - title: Awards & Scholarships
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## **ISOCC Chip Design Contest Dest Poster Award**, *2022*
      ## **Microsoft Research Asia Fellowship Nomination Award**, *2022*
      ## **IEEE Solid-State Circuits Society ISSCC Student Travel Grant Award**, *2022*
      ## **28th Samsung HumanTech Paper Award (Circuit Design) Bronze Prize**, *2022*


  - title: Activities
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## **[Invited Talk]** ***Apple Neural Engine Team Talk (San Jose, CA)***, "CamPU: A Multi-Camera Processing Unit for Deep Learning-based 3D Spatial Computing Systems," *2024*
      
      ## **[Invited Talk]** ***Google TPU Architect Team Talk (San Jose, CA)***, "Circuit, Architecture, and Software Co-design of a Bit-slice Architecture for Dense and Sparse DNN Accelerations," *2024*      
          
      ## **[Invited Talk]** ***Samsung AI Forum 2023 Poster Session Presenter***, *2023*
      
      ## **[Invited Talk]** ***Samsung Electronics DRAM Design Team Talk***, *2023*
      
      ## **[Invited Talk]** ***Apple Neural Engine Team Talk (San Jose, CA)***, "Sibia: Signed Bit-slice Architecture for Dense DNN Acceleration with Slice-level Sparsity Exploitation," *2023*
        
      ## **[Invited Talk]** ***Apple Neural Engine Team Talk (San Jose, CA)***, "DSPU: A 281.6mW Real-Time Depth Signal Processing Unit for Deep Learning-based Dense RGB-D Data Acquisition with Depth Fusion and 3D B-Box Extraction," *2022*

      ## **[Consultation]** ***Expert Consultation on IITP ICT R&D Projects***,*2023*

      ## **[Journal Reviewer]** ***IEEE Transactions on Very Large Scale Integration Systems***, *2024*
      
      ## **[Journal Reviewer]** ***Elsevier Knowledge-Based Systems***, *2024*
      
      ## **[Journal Reviewer]** ***Nature Scientific Reports***, *2024*
      
      ## **[Journal Reviewer]** ***IEEE Journal of Solid-State Circuits***, *2023*
      
      ## **[Journal Reviewer]** ***Springer The Journal of Supercomputing***, *2023*
      
      ## **[Journal Reviewer]** ***IEEE Transaction on Circuits and Systems I***, *2021, 2022*
      
      ## **[System Demo]** ***ACM/IEEE ISLPED Design Contest Presenter***, *2022*
      
      ## **[System Demo]** ***IEEE ISSCC Demonstration Session Presenter***, *2022*          
      
      ## **[International Exchange Program]** ***Summer Session, UC Berkeley***, *2016*

  - title: Patent
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## 1. "STEREOSCOPIC 360-DEGREE IMAGE/VIDEO GENERATION AND 3D DISPLAY SYSTEM," *United States Patent Application*
    
      ## 2. "APPARATUS AND METHOD FOR GENERATING SIGNED BIT SLICE, SIGNED BIT SLICE CALCULATOR, AND ARTIFICIAL INTELLIGENCE NEURAL NETWORK ACCELERATOR TO WHICH THE SAME IS APPLIED,” *United States Patent Application*
      
      ## 3. “CONJUGATE GRADIENT ACCELERATION APPARATUS USING BAND MATRIX COMPRESSION IN DEPTH FUSION TECHNOLOGY,” *United States Patent Application*
      
      ## 4. "3D POINT CLOUD-BASED DEEP LEARNING NEURAL NETWORK ACCELERATION APPARATUS AND METHOD,” *United States Patent Application*

      ## 5. "스테레오스코픽 360도 이미지/영상 생성 및 3차원 디스플레이 시스템", *Korea Patent Application*
      
      ## 6. “부호형 비트 슬라이스 생성기 및 그 방법과, 부호형 비트 슬라이스 연산기와, 이들을 적용한 인공지능 신경망 가속장치”, *Korean Patent Application*
      
      ## 7. “3D 포인트 클라우드 기반 딥러닝 신경망 가속 장치 및 그 방법”, *Korean Patent Application*
      
      ## 8. “뎁스 퓨전 기술에서의 띠행렬 압축을 이용한 켤레기울기 가속 장치”, *Korean Granted Patent, 10-2600979*
 

      
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
